export const FALLBACK_BOB_VERSION = '0.43.0';
export const FALLBACK_NITRO_MODULES_VERSION = '0.36.5';
export const SUPPORTED_MONOREPO_CONFIG_VERSION = '0.4.0';
export const SUPPORTED_REACT_NATIVE_VERSION = '0.86.2';
export const SUPPORTED_EXPO_SDK_VERSION = '57';
